## Atividade - Aula 03 - Treinee Dados e IA - ScitecJr

### Inicializar

- Importar biblioteca Pandas

In [1]:
import pandas as pd

- Abrir dataset escolhido (**Synthetic Ecommerce Order Risk Dataset**)

In [2]:
df = pd.read_csv('synthetic_ecommerce_order_risk_dataset.csv')
df

,order_id,order_date,country,device_type,traffic_source,payment_method,product_category,customer_age_days,previous_orders,avg_order_value_eur,...,shipping_distance_km,delivery_days_estimated,late_delivery_risk,address_mismatch,high_risk_ip,customer_support_contacts,review_score,is_returned,is_fraud,risk_label
0,ORD-2024-001936,2024-01-03,Belgium,Mobile,Paid Ads,Credit Card,Sports,381,3,28.66,...,105.7,5,0,0,0,0,4.4,0,0,Normal
1,ORD-2025-006495,2025-11-26,Netherlands,Desktop,Email,Debit Card,Garden,561,6,41.93,...,528.2,4,0,0,0,0,4.8,0,0,Normal
2,ORD-2023-001721,2023-11-07,Netherlands,Mobile,Organic Search,Debit Card,Garden,324,2,102.67,...,175.1,5,0,0,0,0,3.3,0,0,Normal
3,ORD-2024-009121,2024-05-28,Netherlands,Mobile,Organic Search,Klarna,Electronics,378,3,72.71,...,271.4,3,0,0,0,0,4.2,1,0,Return Risk
4,ORD-2025-000361,2025-01-31,Netherlands,Desktop,Direct,Bank Transfer,Home & Kitchen,447,5,52.26,...,285.3,3,0,1,0,0,5.0,0,0,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,ORD-2023-011965,2023-02-19,France,Mobile,Social Media,Credit Card,Garden,742,3,25.75,...,121.4,3,0,0,0,1,4.5,0,0,Normal
11996,ORD-2023-005192,2023-05-12,France,Mobile,Organic Search,Debit Card,Fashion,152,1,96.29,...,225.5,4,0,0,0,0,5.0,0,0,Normal
11997,ORD-2024-005391,2024-06-13,Germany,Mobile,Organic Search,Credit Card,Fashion,130,0,114.14,...,669.6,5,0,0,0,0,4.5,0,0,Normal
11998,ORD-2025-000861,2025-04-04,Poland,Desktop,Marketplace,PayPal,Fashion,203,1,21.60,...,229.4,5,0,0,0,0,4.4,0,0,Normal
11999,ORD-2024-007271,2024-05-23,Netherlands,Desktop,Organic Search,PayPal,Beauty,288,2,35.58,...,406.6,3,0,0,0,1,3.7,0,0,Normal

In [3]:
df.info(memory_usage='deep')

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 23 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   order_id                   12000 non-null  str
 1   order_date                 12000 non-null  str
 2   country                    12000 non-null  str
 3   device_type                12000 non-null  str
 4   traffic_source             12000 non-null  str
 5   payment_method             12000 non-null  str
 6   product_category           12000 non-null  str
 7   customer_age_days          12000 non-null  int64
 8   previous_orders            12000 non-null  int64
 9   avg_order_value_eur        12000 non-null  float64
 10  order_value_eur            12000 non-null  float64
 11  quantity                   12000 non-null  int64
 12  discount_rate              12000 non-null  float64
 13  shipping_distance_km       12000 non-null  float64
 14  delivery_days_estimated    12000 non-null  int64
 15  late_delivery_risk         12000 non-null  int64
 16  address_mismatch           12000 non-null  int64
 17  high_risk_ip               12000 non-null  int64
 18  customer_support_contacts  12000 non-null  int64
 19  review_score               12000 non-null  float64
 20  is_returned                12000 non-null  int64
 21  is_fraud                   12000 non-null  int64
 22  risk_label                 12000 non-null  str
dtypes: float64(5), int64(10), str(8)
memory usage: 6.7 MB

In [4]:
df.memory_usage(deep=True)

Index                           132
order_id                     768000
order_date                   708000
country                      678575
device_type                  663813
traffic_source               708901
payment_method               699715
product_category             694628
customer_age_days             96000
previous_orders               96000
avg_order_value_eur           96000
order_value_eur               96000
quantity                      96000
discount_rate                 96000
shipping_distance_km          96000
delivery_days_estimated       96000
late_delivery_risk            96000
address_mismatch              96000
high_risk_ip                  96000
customer_support_contacts     96000
review_score                  96000
is_returned                   96000
is_fraud                      96000
risk_label                   667143
dtype: int64

### Otimizar Dataset:
Cenário considerado: mostrar para o cliente as relações entre os tipos de tráfego e a permanência / interesse do comprador

- Remoção das colunas irrelevantes para o contexto

In [5]:
df = df.drop(columns=['order_id', 'payment_method', 'customer_age_days', 'delivery_days_estimated', 'late_delivery_risk', 'address_mismatch', 'high_risk_ip', 'customer_support_contacts', 'is_returned', 'is_fraud'])
df

,order_date,country,device_type,traffic_source,product_category,previous_orders,avg_order_value_eur,order_value_eur,quantity,discount_rate,shipping_distance_km,review_score,risk_label
0,2024-01-03,Belgium,Mobile,Paid Ads,Sports,3,28.66,33.71,2,0.12,105.7,4.4,Normal
1,2025-11-26,Netherlands,Desktop,Email,Garden,6,41.93,73.29,3,0.03,528.2,4.8,Normal
2,2023-11-07,Netherlands,Mobile,Organic Search,Garden,2,102.67,55.49,1,0.05,175.1,3.3,Normal
3,2024-05-28,Netherlands,Mobile,Organic Search,Electronics,3,72.71,112.54,5,0.22,271.4,4.2,Return Risk
4,2025-01-31,Netherlands,Desktop,Direct,Home & Kitchen,5,52.26,55.32,8,0.25,285.3,5.0,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,2023-02-19,France,Mobile,Social Media,Garden,3,25.75,25.75,1,0.31,121.4,4.5,Normal
11996,2023-05-12,France,Mobile,Organic Search,Fashion,1,96.29,118.35,2,0.09,225.5,5.0,Normal
11997,2024-06-13,Germany,Mobile,Organic Search,Fashion,0,114.14,114.13,1,0.08,669.6,4.5,Normal
11998,2025-04-04,Poland,Desktop,Marketplace,Fashion,1,21.60,25.58,1,0.23,229.4,4.4,Normal
11999,2024-05-23,Netherlands,Desktop,Organic Search,Beauty,2,35.58,43.60,2,0.19,406.6,3.7,Normal

In [6]:
df.info(memory_usage='deep')

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_date            12000 non-null  str
 1   country               12000 non-null  str
 2   device_type           12000 non-null  str
 3   traffic_source        12000 non-null  str
 4   product_category      12000 non-null  str
 5   previous_orders       12000 non-null  int64
 6   avg_order_value_eur   12000 non-null  float64
 7   order_value_eur       12000 non-null  float64
 8   quantity              12000 non-null  int64
 9   discount_rate         12000 non-null  float64
 10  shipping_distance_km  12000 non-null  float64
 11  review_score          12000 non-null  float64
 12  risk_label            12000 non-null  str
dtypes: float64(5), int64(2), str(6)
memory usage: 4.6 MB

In [7]:
df.memory_usage(deep=True)

Index                      132
order_date              708000
country                 678575
device_type             663813
traffic_source          708901
product_category        694628
previous_orders          96000
avg_order_value_eur      96000
order_value_eur          96000
quantity                 96000
discount_rate            96000
shipping_distance_km     96000
review_score             96000
risk_label              667143
dtype: int64

- Conversão dos tipos das colunas

In [8]:
df['device_type'].unique()

<StringArray>
['Mobile', 'Desktop', 'Tablet']
Length: 3, dtype: str

In [9]:
df['device_type'] = df['device_type'].map({'Mobile': 0, 'Desktop': 1, 'Tablet': 2}).astype('bool')

In [10]:
df['product_category'].unique()

<StringArray>
[        'Sports',         'Garden',    'Electronics', 'Home & Kitchen',
   'Pet Supplies',         'Beauty',           'Toys',        'Fashion']
Length: 8, dtype: str

In [11]:
df['product_category'] = df['product_category'].map({'Sports': 0, 'Garden': 1, 'Electronics': 2, 'Home & Kitchen': 3, 'Pet Supplies': 4, 'Beauty': 5, 'Toys': 6, 'Fashion': 7}).astype('category')

In [12]:
df['risk_label'].unique()

<StringArray>
['Normal', 'Return Risk', 'Fraud Risk']
Length: 3, dtype: str

In [13]:
df['risk_label'] = df['risk_label'].map({'Normal': 0, 'Return Risk': 1, 'Fraud Risk': 2}).astype('bool')

In [14]:
df

,order_date,country,device_type,traffic_source,product_category,previous_orders,avg_order_value_eur,order_value_eur,quantity,discount_rate,shipping_distance_km,review_score,risk_label
0,2024-01-03,Belgium,False,Paid Ads,0,3,28.66,33.71,2,0.12,105.7,4.4,False
1,2025-11-26,Netherlands,True,Email,1,6,41.93,73.29,3,0.03,528.2,4.8,False
2,2023-11-07,Netherlands,False,Organic Search,1,2,102.67,55.49,1,0.05,175.1,3.3,False
3,2024-05-28,Netherlands,False,Organic Search,2,3,72.71,112.54,5,0.22,271.4,4.2,True
4,2025-01-31,Netherlands,True,Direct,3,5,52.26,55.32,8,0.25,285.3,5.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,2023-02-19,France,False,Social Media,1,3,25.75,25.75,1,0.31,121.4,4.5,False
11996,2023-05-12,France,False,Organic Search,7,1,96.29,118.35,2,0.09,225.5,5.0,False
11997,2024-06-13,Germany,False,Organic Search,7,0,114.14,114.13,1,0.08,669.6,4.5,False
11998,2025-04-04,Poland,True,Marketplace,7,1,21.60,25.58,1,0.23,229.4,4.4,False
11999,2024-05-23,Netherlands,True,Organic Search,5,2,35.58,43.60,2,0.19,406.6,3.7,False

- Amostra e resultado final na memória

In [15]:
df.sample(10)

,order_date,country,device_type,traffic_source,product_category,previous_orders,avg_order_value_eur,order_value_eur,quantity,discount_rate,shipping_distance_km,review_score,risk_label
7155,2023-04-29,Netherlands,False,Paid Ads,4,0,45.65,23.35,1,0.26,255.6,4.1,True
6794,2023-08-02,Italy,True,Paid Ads,3,0,22.34,25.40,1,0.03,548.2,4.4,False
10018,2023-08-15,Netherlands,False,Marketplace,1,2,38.41,24.53,1,0.02,580.7,4.9,False
11606,2023-12-20,Italy,False,Direct,3,1,16.91,23.73,1,0.27,801.5,4.9,False
1276,2024-06-26,Germany,False,Marketplace,2,3,88.23,243.22,1,0.03,634.0,4.1,False
11662,2023-07-24,Netherlands,False,Social Media,4,3,54.37,37.88,1,0.15,541.6,5.0,False
9365,2024-03-02,Germany,True,Social Media,7,3,41.31,85.93,4,0.27,45.5,4.2,False
5748,2025-04-02,Germany,False,Marketplace,3,2,41.68,90.43,1,0.06,183.1,5.0,False
10389,2025-11-10,France,True,Social Media,2,2,24.23,99.79,2,0.01,133.7,4.4,False
627,2023-01-09,Netherlands,True,Direct,1,2,72.50,66.92,2,0.07,324.1,5.0,False

In [16]:
df.info(memory_usage='deep')

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_date            12000 non-null  str
 1   country               12000 non-null  str
 2   device_type           12000 non-null  bool
 3   traffic_source        12000 non-null  str
 4   product_category      12000 non-null  category
 5   previous_orders       12000 non-null  int64
 6   avg_order_value_eur   12000 non-null  float64
 7   order_value_eur       12000 non-null  float64
 8   quantity              12000 non-null  int64
 9   discount_rate         12000 non-null  float64
 10  shipping_distance_km  12000 non-null  float64
 11  review_score          12000 non-null  float64
 12  risk_label            12000 non-null  bool
dtypes: bool(2), category(1), float64(5), int64(2), str(3)
memory usage: 2.7 MB

In [17]:
df.memory_usage(deep=True)

Index                      132
order_date              708000
country                 678575
device_type              12000
traffic_source          708901
product_category         12064
previous_orders          96000
avg_order_value_eur      96000
order_value_eur          96000
quantity                 96000
discount_rate            96000
shipping_distance_km     96000
review_score             96000
risk_label               12000
dtype: int64

### Resumo final e exportação da planilha reduzida

In [18]:
df.describe()

,previous_orders,avg_order_value_eur,order_value_eur,quantity,discount_rate,shipping_distance_km,review_score
count,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000
mean,1.943417,48.940278,61.053339,2.171833,0.146857,479.196567,4.412433
std,1.902590,28.716864,55.540429,1.625534,0.113934,330.305205,0.545286
min,0.000000,8.000000,5.000000,1.000000,0.000000,5.000000,1.300000
25%,1.000000,29.070000,26.617500,1.000000,0.060000,236.100000,4.100000
50%,1.000000,42.100000,45.335000,2.000000,0.120000,404.450000,4.500000
75%,3.000000,61.010000,75.952500,3.000000,0.210000,645.225000,4.900000
max,13.000000,350.450000,810.750000,8.000000,0.750000,2589.700000,5.000000

In [19]:
df.to_csv('synthetic_ecommerce_order_risk_dataset_simplified.csv', index=False)

### Possíveis ralações

Método de tráfego x número de pedidos anteriores

In [20]:
df.groupby('traffic_source')['previous_orders'].mean()

traffic_source
Direct            1.920068
Email             2.023359
Marketplace       1.993464
Organic Search    1.945085
Paid Ads          1.947508
Social Media      1.887732
Name: previous_orders, dtype: float64

Compras por tipo de tráfego em cada país

In [21]:
df.groupby('country')['traffic_source'].value_counts()

country      traffic_source
Belgium      Organic Search    471
             Paid Ads          427
             Social Media      345
             Direct            306
             Marketplace       264
             Email             157
France       Organic Search    311
             Paid Ads          299
             Social Media      239
             Marketplace       184
             Direct            173
             Email              99
Germany      Organic Search    431
             Paid Ads          362
             Social Media      311
             Direct            240
             Marketplace       194
             Email             112
Italy        Organic Search    219
             Paid Ads          204
             Social Media      175
             Direct            143
             Marketplace       104
             Email              70
Netherlands  Organic Search    821
             Paid Ads          755
             Social Media      634
             Direct            487
             Marketplace       433
             Email             258
Poland       Organic Search    223
             Paid Ads          191
             Social Media      152
             Direct            135
             Marketplace       105
             Email              56
Spain        Organic Search    266
             Paid Ads          227
             Social Media      206
             Direct            157
             Marketplace       133
             Email              81
Turkey       Organic Search    208
             Paid Ads          183
             Social Media      147
             Direct            123
             Marketplace       113
             Email              66
Name: count, dtype: int64

Categorias mais compradas em cada país

In [22]:
df.groupby('country')['product_category'].value_counts().sort_values(ascending=False)

country      product_category
Netherlands  3                   690
             2                   565
             7                   462
             1                   434
Belgium      3                   406
                                ...
Spain        4                    78
Turkey       4                    70
Italy        4                    66
Turkey       5                    61
Poland       4                    59
Name: count, Length: 64, dtype: int64

### Visualização Gráfica

- Importar as bibliotecas para análise e criação de gráficos comparativos (Plotly e SciPy)
    - execução de `pip install --upgrade nbformat` & `pip install statsmodels`

In [23]:
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
from plotly.subplots import make_subplots
from scipy.stats import pearsonr

pio.renderers.default = "notebook_connected"

Gráfico 1: Análise Comparativa de Faturamento por Canal de Tráfego
- Agrupa os dados por origem de tráfego para expor quais canais geram maior retorno financeiro e qual possui o melhor Ticket Médio

In [ ]:
traffic_insights = df.groupby('traffic_source').agg(faturamento_total=('order_value_eur', 'sum'),ticket_medio=('order_value_eur', 'mean')).reset_index()

fig_traffic = go.Figure()

fig_traffic.add_trace(go.Bar(
    x=traffic_insights['traffic_source'],
    y=traffic_insights['faturamento_total'],
    text=traffic_insights['faturamento_total'].apply(lambda x: f'€ {x:,.0f}'),
    textposition='auto',
    marker=dict(
        color=traffic_insights['ticket_medio'],
        colorscale='Viridis',
        showscale=True,
        colorbar=dict(title="Ticket Médio (€)")
    )
))

fig_traffic.update_layout(
    title='Análise Comercial: Faturamento Total e Ticket Médio por Canal de Tráfego',
    template='plotly_white',
    xaxis_title="Origem do Tráfego",
    yaxis_title="Volume Financeiro Total (EUR)",
    height=500
)

fig_traffic.show()

Gráfico 2: Painel Comparativo Multi-variável (Subplots) de Mercados por País
- Criar uma visualização lado a lado (Subplots) para comparar diretamente o faturamento total gerado contra a quantidade total de itens vendidos em cada país

In [25]:
country_insights = df.groupby('country').agg(
    faturamento=('order_value_eur', 'sum'),
    quantidade_itens=('quantity', 'sum')
).sort_values(by='faturamento', ascending=False).reset_index()

fig_subplots = make_subplots(
    rows=1, cols=2, 
    subplot_titles=("Faturamento Total acumulado por País", "Quantidade Total de Itens por País"),
    shared_xaxes=False
)

fig_subplots.add_trace(
    go.Bar(
        x=country_insights['country'], 
        y=country_insights['faturamento'], 
        name='Faturamento (€)', 
        marker_color='#1f77b4',
        text=country_insights['faturamento'].round(0),
        textposition='auto'
    ),
    row=1, col=1
)

fig_subplots.add_trace(
    go.Bar(
        x=country_insights['country'], 
        y=country_insights['quantidade_itens'], 
        name='Unidades Vendidas', 
        marker_color='#2ca02c',
        text=country_insights['quantidade_itens'],
        textposition='auto'
    ),
    row=1, col=2
)

fig_subplots.update_layout(
    title_text="Painel Macro de Desempenho Comercial Internacional",
    template='plotly_white',
    showlegend=True,
    height=500
)
fig_subplots.show()

Gráfico 3: Validação Comercial Estatística - Descontos vs. Valor de Compra
- Mendir estatisticamente a influência das estratégias de precificação utilizando a Correlação de Pearson (`pearsonr`) para verificar se maiores taxas de desconto resultam em compras de valor maior, projetando os dados em um gráfico de dispersão com linha de tendência

In [26]:
coef_corr, p_value = pearsonr(df['discount_rate'], df['order_value_eur'])

print(f"Coeficiente de Correlação de Pearson: {coef_corr:.4f}")
print(f"Significância Estatística (P-value): {p_value:.4e}")

fig_disp = px.scatter(
    df.sample(n=1000, random_state=42), 
    x='discount_rate', 
    y='order_value_eur',
    trendline='ols',
    title=f'Impacto Comercial de Campanhas de Desconto (Correlação: {coef_corr:.2f})',
    labels={'discount_rate': 'Taxa de Desconto Aplicada', 'order_value_eur': 'Valor Total do Pedido (EUR)'},
    opacity=0.7,
    color_discrete_sequence=['#ff7f0e']
)

fig_disp.update_layout(template='plotly_white')
fig_disp.show()

Coeficiente de Correlação de Pearson: 0.0051
Significância Estatística (P-value): 5.7429e-01